controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

      left_wheel_names: ['left_wheel_joint']
      right_wheel_names: ['right_wheel_joint']

      publish_rate: 50.0 # Hz
      odom_frame_id: odom
      base_frame_id: base_link
      pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
      twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

      # Rodas
      wheel_separation: 0.34 # Dist√¢ncia entre as rodas (2 * wheel_offset_y do XACRO)
      wheel_radius: 0.05     # Raio da roda (wheel_radius do XACRO)

      # Limites de velocidade (opcional, mas recomendado)
      linear:
        x:
          has_velocity_limits: true
          max_velocity: 0.5
          has_acceleration_limits: true
          max_acceleration: 1.0
      angular:
        z:
          has_velocity_limits: true
          max_velocity: 1.0
          has_acceleration_limits: true
          max_acceleration: 2.0
